# Generated by Django 3.1.4 on 2021-01-08 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_study'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='study',
            table='study',
        ),
    ]
