# Generated by Django 3.1.4 on 2021-01-08 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0005_auto_20210108_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={'verbose_name': 'asdf'},
        ),
    ]
