# Generated by Django 3.1.4 on 2021-01-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0006_auto_20210108_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={},
        ),
        migrations.AlterField(
            model_name='study',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
