# Generated by Django 3.1.4 on 2021-01-10 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0007_auto_20210108_1240'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Study',
        ),
    ]
