# Generated by Django 3.1.4 on 2021-01-08 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210105_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follower',
            new_name='folFolower',
        ),
    ]
